package br.com.embracon.teamposition.domain.enumeration;

public enum ReportEnum {

	BRANCH_CC(0),
	BRANCH_CODE(1),
	BRANCH_NAME(2),
	AREGIONAL_CODE(3),
	AREGIONAL_NAME(4),
	DIR_CODE(5),
	REGIONAL_REGISTRY(6),
	REGIONAL_LOGIN_SCE(7),
	REGIONAL_NAME(8),
	REGIONAL_SITUATION(9),
	MANAGER_CODE(10),
	MANAGER_REGISTRY(11),
	MANAGER_LOGIN_SCE(12),
	MANAGER_NAME(13),
	MANAGER_SITUATION(14),
	MANAGER_ORIGN_TRANSFER(15),
	SUPERVISOR_CODE(16),
	SUPERVISOR_REGISTRY(17),
	SUPERVISOR_LOGIN_SCE(18),
	SUPERVISOR_NAME(19),
	SUPERVISOR_SITUATION(20),
	SUPERVISOR_ORIGIN_TRANSFER(21),
	SELLER_CODE(22),
	SELLER_REGISTRY(23),
	SELLER_LOGIN_SCE(24),
	SELLER_NAME(25),
	ADMISSION_DATE(26),
	SELLER_SITUATION(27),
	SELLER_ORIGN_TRANSFER(28),
	RESELLER_CODE(29),
	RESELLER_NAME(30),
	ADMINISTRATIVES(31),
	LEADER(32);
	
	private int index;
	
	private ReportEnum(int index) {
		this.index = index;
	}
	
	public int index() {
		return this.index;
	}
	
	
}
