
package br.com.embracon.wsteamposition.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "inventory-gp", targetNamespace = "http://ws.wsteamposition.embracon.com.br/", wsdlLocation = "http://cetomcat-des.embraconnet.com.br:8080/ws-inventory-gp/inventory-gp?wsdl")
public class TeamPosition_Service
    extends Service
{

    private final static URL TEAMPOSITION_WSDL_LOCATION;
    private final static WebServiceException TEAMPOSITION_EXCEPTION;
    private final static QName TEAMPOSITION_QNAME = new QName("http://ws.wsteamposition.embracon.com.br/", "inventory-gp");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://cetomcat-des.embraconnet.com.br:8080/ws-inventory-gp/inventory-gp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEAMPOSITION_WSDL_LOCATION = url;
        TEAMPOSITION_EXCEPTION = e;
    }

    public TeamPosition_Service() {
        super(__getWsdlLocation(), TEAMPOSITION_QNAME);
    }

    public TeamPosition_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEAMPOSITION_QNAME, features);
    }

    public TeamPosition_Service(URL wsdlLocation) {
        super(wsdlLocation, TEAMPOSITION_QNAME);
    }

    public TeamPosition_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEAMPOSITION_QNAME, features);
    }

    public TeamPosition_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TeamPosition_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TeamPosition
     */
    @WebEndpoint(name = "inventory-gpPort")
    public TeamPosition getTeamPositionPort() {
        return super.getPort(new QName("http://ws.wsteamposition.embracon.com.br/", "inventory-gpPort"), TeamPosition.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TeamPosition
     */
    @WebEndpoint(name = "inventory-gpPort")
    public TeamPosition getTeamPositionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wsteamposition.embracon.com.br/", "inventory-gpPort"), TeamPosition.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEAMPOSITION_EXCEPTION!= null) {
            throw TEAMPOSITION_EXCEPTION;
        }
        return TEAMPOSITION_WSDL_LOCATION;
    }

}
