
package br.com.embracon.wsteamposition.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.com.embracon.wsembraconvo.teamposition.Branch;
import br.com.embracon.wsembraconvo.teamposition.Collaborator;
import br.com.embracon.wsembraconvo.teamposition.Regional;
import br.com.embracon.wsentity.domain.entity.teamposition.BranchInfo;
import br.com.embracon.wsentity.domain.entity.teamposition.CollaboratorInfo;
import br.com.embracon.wsentity.domain.entity.teamposition.RegionalInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "inventory-gp", targetNamespace = "http://ws.wsteamposition.embracon.com.br/")
@XmlSeeAlso({
    br.com.embracon.wsembraconvo.ObjectFactory.class,
    br.com.embracon.wsembraconvo.authenticator.ObjectFactory.class,
    br.com.embracon.wsembraconvo.teamposition.ObjectFactory.class,
    br.com.embracon.wsentity.domain.ObjectFactory.class,
    br.com.embracon.wsentity.domain.entity.teamposition.ObjectFactory.class,
    br.com.embracon.wsteamposition.ws.ObjectFactory.class
})
public interface TeamPosition {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.embracon.wsentity.domain.entity.teamposition.BranchInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBranch", targetNamespace = "http://ws.wsteamposition.embracon.com.br/", className = "br.com.embracon.wsteamposition.ws.FindBranch")
    @ResponseWrapper(localName = "findBranchResponse", targetNamespace = "http://ws.wsteamposition.embracon.com.br/", className = "br.com.embracon.wsteamposition.ws.FindBranchResponse")
    public BranchInfo findBranch(
        @WebParam(name = "arg0", targetNamespace = "")
        Branch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.embracon.wsentity.domain.entity.teamposition.RegionalInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRegional", targetNamespace = "http://ws.wsteamposition.embracon.com.br/", className = "br.com.embracon.wsteamposition.ws.FindRegional")
    @ResponseWrapper(localName = "findRegionalResponse", targetNamespace = "http://ws.wsteamposition.embracon.com.br/", className = "br.com.embracon.wsteamposition.ws.FindRegionalResponse")
    public RegionalInfo findRegional(
        @WebParam(name = "arg0", targetNamespace = "")
        Regional arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.embracon.wsentity.domain.entity.teamposition.CollaboratorInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCollaborator", targetNamespace = "http://ws.wsteamposition.embracon.com.br/", className = "br.com.embracon.wsteamposition.ws.FindCollaborator")
    @ResponseWrapper(localName = "findCollaboratorResponse", targetNamespace = "http://ws.wsteamposition.embracon.com.br/", className = "br.com.embracon.wsteamposition.ws.FindCollaboratorResponse")
    public CollaboratorInfo findCollaborator(
        @WebParam(name = "arg0", targetNamespace = "")
        Collaborator arg0);

}
