INSERT INTO MF_PERFIL (COD_PERFIL, ATIVO, DESCRICAO, EDICAO, EXCLUSAO, NOME, LEITURA, CADASTRO, TIPO, AREA)
VALUES(SEQ_MF_PERFIL.NEXTVAL,'A','POSIÇÃO EQUIPE - GERENTE','S','N','PE - GERENTE','S','S','SYSTEM', 'CM');

INSERT INTO MF_PERFIL (COD_PERFIL, ATIVO, DESCRICAO, EDICAO, EXCLUSAO, NOME, LEITURA, CADASTRO, TIPO, AREA)
VALUES(SEQ_MF_PERFIL.NEXTVAL,'A','POSIÇÃO EQUIPE - ADMIN.','S','N','PE - ADMIN.','S','S','SYSTEM', 'CM');

INSERT INTO MF_PERFIL (COD_PERFIL, ATIVO, DESCRICAO, EDICAO, EXCLUSAO, NOME, LEITURA, CADASTRO, TIPO, AREA)
VALUES(SEQ_MF_PERFIL.NEXTVAL,'A','POSIÇÃO EQUIPE - COMERCIAL','S','N','PE - COMERCIAL','S','S','SYSTEM', 'CM');
